default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dev_cherapp
  username: pavirami
  password: pgpwd@26
  host: localhost
  port: 5432

# test:
#   <<: *default
#   database: test_cherapp

# production:
#   <<: *default
#   database: production_cherapp
